# Site details
title: C++ Reference (Romanian)
description: Site pentru conținut legat de C++ în limba română. Creat pentru a partaja chestii legate de C++ cu colegii mei.

# Important site variables
domain: thefirefourteen.github.io
url: https://thefirefourteen.github.io
baseurl: /cpp-reference-romanian/

# Author data
# For more socials, see: "https://github.com/jekyll/minima/blob/v2.5.1/_includes/social.html"
email: andreifl@duck.com
github_username: thefirefourteen

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
